services:
    php-cli:
        build:
            context: docker
            dockerfile: development/php-cli/Dockerfile
        environment:
            APP_ENV: local
            APP_DEBUG: 1
        volumes:
            - ./:/app

    nginx:
        build:
            context: docker
            dockerfile: development/nginx/Dockerfile
        depends_on:
            php-fpm:
                condition: service_started
        volumes:
            - ./:/app
        ports:
            - "8080:80"

    php-fpm:
        build:
            context: docker
            dockerfile: development/php-fpm/Dockerfile
        environment:
            APP_ENV: local
            APP_DEBUG: 1
            DB_HOST: postgres
            DB_USER: app
            DB_PASSWORD_FILE: /run/secrets/db_password
            DB_NAME: app
        depends_on:
            postgres:
                condition: service_started
        volumes:
            - ./:/app
        secrets:
            - db_password

    postgres:
        image: postgres:16.3-alpine
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD_FILE: /run/secrets/db_password
            POSTGRES_DB: app
        secrets:
            - db_password
        volumes:
            - api-postgres:/var/lib/postgresql/data
        ports:
            - "54321:5432"

secrets:
    db_password:
        file: ./docker/development/secrets/db_password

volumes:
    api-postgres:
