services:
    php-cli:
        build:
            context: docker
            dockerfile: development/php-cli/Dockerfile
        environment:
            APP_ENV: local
            APP_DEBUG: 1
            DB_HOST: postgres
        volumes:
            - './:/app'
    nginx:
        build:
            context: docker
            dockerfile: development/nginx/Dockerfile
        depends_on:
            php-fpm:
                condition: service_started
        volumes:
            - './:/app'
        ports:
            - '8080:80'
    php-fpm:
        build:
            context: docker
            dockerfile: development/php-fpm/Dockerfile
        environment:
            APP_ENV: local
            APP_DEBUG: 1
            DB_HOST: postgres
        depends_on:
            postgres:
                condition: service_started
        volumes:
            - './:/app'
    postgres:
        image: 'postgres:16.3-alpine'
        environment:
            POSTGRES_DB: '${DB_DATABASE:-laravel}'
            POSTGRES_USER: '${DB_USERNAME:-sail}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'api-postgres:/var/lib/postgresql/data'
        ports:
            - '54321:5432'

volumes:
    api-postgres:
